/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-bright': '#393939',
        'on-background': '#e5e2e1',
        'tertiary-fixed': '#e5e2e1',
        'surface-container-highest': '#353535',
        'on-secondary-fixed': '#320047',
        'on-secondary': '#520072',
        'secondary-fixed-dim': '#ebb2ff',
        'on-secondary-fixed-variant': '#74009f',
        'surface-container-high': '#2a2a2a',
        background: '#131313',
        // Lightened from #605e5e to clear WCAG AA (4.5:1) on #131313, including
        // where it is rendered at opacity-80 in the footer.
        'on-tertiary-container': '#9a9896',
        'secondary-fixed': '#f8d8ff',
        'outline-variant': '#3b494b',
        'on-error': '#690005',
        'on-primary-container': '#006970',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        'on-surface': '#e5e2e1',
        'surface-container-low': '#1c1b1b',
        'surface-tint': '#00dbe9',
        'on-tertiary-fixed': '#1c1b1b',
        tertiary: '#f9f5f5',
        'secondary-container': '#b600f8',
        'on-error-container': '#ffdad6',
        'primary-fixed-dim': '#00dbe9',
        'inverse-primary': '#006970',
        'surface-dim': '#131313',
        'tertiary-container': '#dcd9d8',
        outline: '#849495',
        'primary-container': '#00f0ff',
        'on-primary-fixed': '#002022',
        'error-container': '#93000a',
        'on-surface-variant': '#b9cacb',
        'on-tertiary-fixed-variant': '#474646',
        'primary-fixed': '#7df4ff',
        'on-secondary-container': '#fff6fc',
        secondary: '#ebb2ff',
        'surface-variant': '#353535',
        'surface-container': '#20201f',
        'tertiary-fixed-dim': '#c9c6c5',
        'on-tertiary': '#313030',
        'surface-container-lowest': '#0e0e0e',
        'on-primary-fixed-variant': '#004f54',
        'on-primary': '#00363a',
        error: '#ffb4ab',
        primary: '#dbfcff',
        surface: '#131313',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-desktop': '64px',
        gutter: '24px',
        'margin-mobile': '20px',
        'stack-unit': '8px',
        'container-max': '1280px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-md': ['var(--font-display)', 'sans-serif'],
        'headline-lg-mobile': ['var(--font-display)', 'sans-serif'],
        'headline-xl': ['var(--font-display)', 'sans-serif'],
        'body-lg': ['var(--font-inter)', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'sans-serif'],
        'code-sm': ['var(--font-jetbrains-mono)', 'monospace'],
        'headline-lg': ['var(--font-display)', 'sans-serif'],
        'label-caps': ['var(--font-jetbrains-mono)', 'monospace'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '500' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'code-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
